### ISSUE TITLE
【Test CI/CD】テスト自動化・品質ゲート統合

### ISSUE THREAD

**Issue by octop162** [octop162/normal-form-app-by-claude#37]
## 概要

CI/CDパイプラインにテスト自動化と品質ゲートを統合します。

### 1. GitHub Actions 統合
- **Pull Request**: テスト自動実行・結果レポート
- **Branch Protection**: テスト通過を必須条件に設定
- **並列実行**: Unit・Integration・E2E テスト並列化

### 2. 品質ゲート
- **コードカバレッジ**: 80%以上を必須条件
- **テスト通過率**: 100%を必須条件
- **静的解析**: ESLint・golangci-lint チェック
- **セキュリティスキャン**: 依存関係・脆弱性チェック

### 3. テスト環境管理
- **Docker統合**: テスト用コンテナ環境
- **データベース**: PostgreSQL テストコンテナ
- **外部APIモック**: 安定したテスト環境

### 4. レポート・通知
- **テスト結果**: HTML・JUnit レポート生成
- **カバレッジレポート**: コードカバレッジ可視化
- **Slack通知**: テスト失敗・成功通知
- **GitHub Status**: PR状態表示

## CI/CD ワークフロー

```yaml
name: Test Suite
on: [pull_request, push]

jobs:
  unit-tests:
    # Go・React Unit Tests
  
  integration-tests:
    # API Integration Tests
  
  e2e-tests:
    # Playwright E2E Tests
  
  quality-gate:
    needs: [unit-tests, integration-tests, e2e-tests]
    # Coverage Check & Security Scan
```

## ファイル構成

```
.github/
├── workflows/
│   ├── test-backend.yml
│   ├── test-frontend.yml
│   ├── test-e2e.yml
│   └── quality-gate.yml
└── test-configs/
    ├── coverage.yml
    └── security-scan.yml
```

## 受け入れ条件

- [ ] GitHub Actions ワークフロー設定
- [ ] Branch Protection Rules 設定
- [ ] コードカバレッジ・品質ゲート設定
- [ ] テスト結果レポート・通知設定
- [ ] Docker テスト環境統合
- [ ] セキュリティスキャン統合
